set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_FLAGS "--target=x86_64-w64-mingw32 --sysroot=D:/Programme/msys64/mingw64")
set(CMAKE_C_FLAGS "--target=x86_64-w64-mingw32 --sysroot=D:/Programme/msys64/mingw64")
add_link_options(-fuse-ld=lld)
add_link_options(-static-libgcc)
add_link_options(-static-libstdc++)
add_link_options(-static -pthread)
set(CMAKE_CXX_CLANG_TIDY clang-tidy)
